### ISSUE TITLE
phd link is broken

### ISSUE THREAD

**Issue by MAKIO135** [isohedral/tactile-js#12]
Link `phd` defined line 155 of [README.md](https://github.com/isohedral/tactile-js/edit/master/README.md) is broken:
```md 
[phd]: http://www.cgl.uwaterloo.ca/csk/phd/
```

**Comment by isohedral** [comment]
Yeah, my home page moved last year. Fixed the link, thanks!

**Comment by MAKIO135** [comment]
Perfect, thanks!

**Comment by MAKIO135** [comment]
ho, there is a second reference to it:
> If you want a quick and free introduction, you could look through Chapters 2 and 4 of my PhD thesis.

The one I was looking for :/

**Comment by isohedral** [comment]
Yup, that one was updated at the same time.

**Comment by MAKIO135** [comment]
ha my bad, needed to reload 😅
Thanks again, the lib looks awesome 👏
